spring:
  docker:
    compose:
      file: docker-compose.yml
      enabled: true
      lifecycle-management: start_only
  cloud:
    stream:
      schema-registry-client:
        endpoint: https://localhost:8990