spring:
  main:
    lazy-initialization: true
    banner-mode: off
    log-startup-info: false
  docker:
    compose:
      enabled: false
  cloud:
    stream:
      schema-registry-client:
        endpoint: ${KAFKA_SCHEMA_REGISTRY_URL}