spring:
  main:
    lazy-initialization: true
    banner-mode: off
    log-startup-info: false
  docker:
    compose:
      enabled: false

app:
  config:
    kafka:
      group-id: spring-boot-tests
      topics:
        creation-topic: com.nbusto.spring.boot.poc.creation.0
        delete-topic: com.nbusto.spring.boot.poc.delete.0

server:
  servlet:
    context-path: /tests