spring:
  docker:
    compose:
      file: docker-compose.yml
      enabled: true
      lifecycle-management: start_only
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081/
management:
  endpoint:
    beans:
      access: read_only
  endpoints:
    web:
      exposure:
        include: '*'