spring:
  main:
    lazy-initialization: true
    banner-mode: off
    log-startup-info: false
  docker:
    compose:
      enabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${KAFKA_SCHEMA_URL}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

app:
  config:
    kafka:
      group-id: spring-boot-tests
      topics:
        creation-topic: com.nbusto.spring.boot.poc.creation.0
        delete-topic: com.nbusto.spring.boot.poc.delete.0

server:
  servlet:
    context-path: /tests