openapi: 3.0.0
info:
  version: 1.1.0
  title: Spring boot test
servers:
  - url: http://localhost:8080
paths:
  /healthcheck:
    get:
      summary: Returns service status
      description: ''
      operationId: healthcheck
      tags:
        - status
      responses:
        '200':
          description: Default error sample response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "UP"
  /doubles/default:
    get:
      summary: Returns a default formatted double
      description: ''
      operationId: default-double
      tags:
        - doubles
      parameters:
        - $ref: "#/components/parameters/doubleParam"
      responses:
        "200":
          description: "Returns a double default formatted"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: number
                    format: double
  /doubles/decimal_comma:
    get:
      summary: Returns a double formatted with decimal comma
      description: ''
      operationId: decimal-double
      tags:
        - doubles
      parameters:
        - $ref: "#/components/parameters/doubleParam"
      responses:
        "200":
          description: "Returns a double formatted with decimal comma"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    pattern: ^-?[0-9]+.?[0-9]*$
components:
  parameters:
    doubleParam:
      name: value
      in: query
      description: Optional double to be returned
      schema:
        type: number
        format: double